### PR TITLE
Feature/notifications

### PR DESCRIPTION
**Pull request by SoneeJohn**
Just added notifications to the app Thoughts?

TODO:

- [x] Add menu item so user can turn notifications on or off

- [ ] Do more tests

- [ ] Maybe when the user clicks the notification we show a table with all the new episodes?

screen shot 2017-11-01 at 6 31 44 pm

screen shot 2017-11-01 at 6 31 38 pm

### CODE REVIEW

**Comment by rdio-ops** [comment]
+1 on this PR. Would love to see this get pulled in.

**Comment by DevBOFH** [comment]
+1 on this PR. Would love to see this get pulled in.

**Comment by insidegui** [comment]
@SoneeJohn Can you implement this item: `Add menu item so user can turn notifications on or off` ?

If you push that, I'll be happy to merge.

**Comment by SoneeJohn** [comment]
@insidegui Would still like to implement `Maybe when the user clicks the notification we show a table with all the new episodes?`

**Comment by SoneeJohn** [comment]
But I'll have to upgrade the project to Swift 4

**Pull request merged**
